### PR TITLE
WIP - Add failing test for issuance hash/txid discrepancy

### PR DESCRIPTION
**Pull request by asoltys**
I seem to be getting a different txid/hash computed for issuance transactions when I decode them with elements core compared to this library. 

I'm assuming elements core is correct but haven't fully investigated yet. In the meantime here's a test fixture with the hex for a regtest issuance transaction and expected txid set to the one I get from Elements Core RPC client version v0.18.1.6-17092fc62

### CODE REVIEW

**Comment by louisinger** [comment]
I think it is all the serialization / de-serialization process for issuance that fails. In fact, issuance transactions are not yet supported in liquidjs-lib. The existing code is inspired from [libwally-core](https://github.com/ElementsProject/libwally-core). There is a [WIP pull request](https://github.com/provable-things/liquidjs-lib/pull/2) for issuance implementation. 
I'll compare serialization with [go-elements](https://github.com/vulpemventures/go-elements/blob/79d835d74155b39b360d60aa3d0cbd17401d5355/transaction/transaction.go#L157) and investigate the problem.

**Comment by asoltys** [comment]
Oh thanks I didn't see that other PR. Looks like you guys have already put a lot of thought and progress into the issue there so I'll close this one.

**Comment by tiero** [comment]
Thanks anyway @asoltys 

We have moved the PR in this repo so we can proceed faster and eventually merge here. https://github.com/vulpemventures/liquidjs-lib/pull/4

Will prioritize this if you think you need issuance done with JS

**Comment by asoltys** [comment]
Sounds good, thanks! I do have a use case for it and I'll be happy to test the PR and try to help out. 

I thought I might be able to work around by generating the issuance tx with elements and just signing it with JS but I don't think the lib let me sign when the txid isn't what it expects it to be. 

I also tried issuing with elements to an address generated with JS thinking maybe I could use it as an input in a second regular spend transaction but even that doesn't work because when it parses the issuance hex as a nonWitnessUtxo for the input, it finds the txid discrepancy there too.

**Pull request closed without merging**
